version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
      nodejs: 14
    commands:
      - echo Installing pip dependencies
      - pip3 install -r requirements.txt
      - echo Installing npm dependencies
      - npm install
  pre_build:
    commands:
      - echo Prebuild ops
  build:
    commands:
      - echo Building the application 
      - echo Building Tailwind CSS
      - npx tailwindcss -o static/css/tailwind.css
      - echo Collecting static files
      - python manage.py collectstatic --noinput
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
