FROM python:3.10-slim

ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE=backend.settings

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git-core \
        build-essential \
        binutils \
        libproj-dev \
        gdal-bin \
        supervisor && \
    rm -rf /var/lib/apt/lists/*

COPY ./home/sahir/Documents/learning/myBlogsWeb/BlogWebsite/requirements /home/codewithmuh-backend/requirements
RUN mkdir -p /home/sahir-backend/media
WORKDIR /home/sahir-backend


RUN pip install --upgrade pip
RUN pip install -r ./requirements/requirements.txt



EXPOSE 8000

RUN mkdir -p /var/logs/codewithmuh


COPY ./django/build-process/docker-backend-django/scripts /home/docker/scripts
COPY ./django/build-process/docker-backend-django/config/supervisor-backend.conf /etc/supervisor/conf.d/supervisor-backend.conf

RUN sed -i 's/\r$//' /home/docker/scripts/boot.sh  && \
        chmod +x /home/docker/scripts/boot.sh



COPY ./django /home/sahir-backend

ENTRYPOINT /home/docker/scripts/boot.sh

